### ISSUE TITLE
PayPal module response issue

### ISSUE THREAD

**Issue by ShapesGraphicStudio** [TeamEver/everpsclickandcollect#1]
Hello,

PayPal response has some issue with this module apparently.
The order does not get validated and the invoice is not created.

PayPal log shows:
`Order validation error : Property EverpsclickandcollectStoreStock->qty is not valid; File: /var/www/vhosts/mydomain.com/httpdocs/classes/ObjectModel.php; Line: 1045;`

Any idea on how to solve this please?

**Comment by CySSoO** [comment]
Hello
Could you try unhooking the module from the PDF hook and tell me?
Hooks are :
- hookDisplayPDFDeliverySlip
- hookDisplayPDFInvoice

**Comment by ShapesGraphicStudio** [comment]
Hi, thanks for your answer, just did it.
I will keep you updated on next order.

In general logs I can also see:
`Exception on hook actionUpdateQuantity for module . Property EverpsclickandcollectStoreStock->qty is not valid`

PS: I forgot to mention that stock handling is set to off in shop configuration.

**Comment by CySSoO** [comment]
I just made a commit, which disables the use of certain hooks if stock management is not active
Can you install this latest version on your store?
https://github.com/TeamEver/everpsclickandcollect/archive/refs/tags/V2.3.5.zip

**Comment by ShapesGraphicStudio** [comment]
Hi, thanks a lot for the reactive handling of this issue!
I just had a new order using PayPal and everything worked fine with this commit.

I'm waiting for a new order with the second payment gateway which was showing some buggy symptoms too and I will get back to you.

**Comment by ShapesGraphicStudio** [comment]
Same thing with the other payment gateway, evrything seems to be fixed with this new commit.

Other symptoms were:

With PayPal, the order and invoice did not display the related products and the associated shipping method.

With Axepta BNP mOdule, the order were validated but the order and invoice did not display the related products and the associated shipping method.

Again, thanks for the quick support!

**Comment by ShapesGraphicStudio** [comment]
I have an upgrade available in the modules, should I update? Does it contain your latest commit?

**Comment by CySSoO** [comment]
You can apply the update, but the previous commit is already in place on your store
Is your problem completely resolved?

**Comment by ShapesGraphicStudio** [comment]
OK thanks.
Everything seems to be fixed yes.
